// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odin.Api.Base.Data;

#nullable disable

namespace Odin.Api.Base.Data.Migrations
{
    [DbContext(typeof(OdinDbContext))]
    [Migration("20260419094024_AddPathwayDocumentsAndProgrammePathways")]
    partial class AddPathwayDocumentsAndProgrammePathways
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecoveryCodesConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            DocumentTypeId = 1,
                            Name = "Passport"
                        },
                        new
                        {
                            DocumentTypeId = 2,
                            Name = "CV"
                        },
                        new
                        {
                            DocumentTypeId = 3,
                            Name = "Degree Certificate"
                        },
                        new
                        {
                            DocumentTypeId = 4,
                            Name = "Language Certificate"
                        },
                        new
                        {
                            DocumentTypeId = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.EnrollmentDocument", b =>
                {
                    b.Property<Guid>("EnrollmentDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnrollmentDocumentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StudentDocumentId");

                    b.HasIndex("StudentEnrollmentId");

                    b.ToTable("EnrollmentDocuments");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.EnrollmentStatus", b =>
                {
                    b.Property<int>("EnrollmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowSetByPartner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EnrollmentStatusId");

                    b.ToTable("EnrollmentStatuses");

                    b.HasData(
                        new
                        {
                            EnrollmentStatusId = 1,
                            AllowSetByPartner = false,
                            Name = "Active"
                        },
                        new
                        {
                            EnrollmentStatusId = 2,
                            AllowSetByPartner = false,
                            Name = "Active (Final Project)"
                        },
                        new
                        {
                            EnrollmentStatusId = 3,
                            AllowSetByPartner = false,
                            Name = "Applicant Withdraw"
                        },
                        new
                        {
                            EnrollmentStatusId = 4,
                            AllowSetByPartner = false,
                            Name = "Cancelled"
                        },
                        new
                        {
                            EnrollmentStatusId = 5,
                            AllowSetByPartner = false,
                            Name = "Deferred"
                        },
                        new
                        {
                            EnrollmentStatusId = 6,
                            AllowSetByPartner = false,
                            Name = "Dismissed"
                        },
                        new
                        {
                            EnrollmentStatusId = 7,
                            AllowSetByPartner = false,
                            Name = "Drop Out"
                        },
                        new
                        {
                            EnrollmentStatusId = 8,
                            AllowSetByPartner = false,
                            Name = "Graduated"
                        },
                        new
                        {
                            EnrollmentStatusId = 9,
                            AllowSetByPartner = false,
                            Name = "Potential Applicant"
                        },
                        new
                        {
                            EnrollmentStatusId = 10,
                            AllowSetByPartner = false,
                            Name = "Potential Applicant Paid"
                        },
                        new
                        {
                            EnrollmentStatusId = 11,
                            AllowSetByPartner = false,
                            Name = "Transferred"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Fido2Credential", b =>
                {
                    b.Property<Guid>("Fido2CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SignatureCounter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transports")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fido2CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("Fido2Credentials");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.FinalProject", b =>
                {
                    b.Property<Guid>("FinalProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalProjectStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supervisor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("FinalProjectId");

                    b.HasIndex("FinalProjectStatusId");

                    b.HasIndex("StudentEnrollmentId")
                        .IsUnique();

                    b.ToTable("FinalProjects");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.FinalProjectStatus", b =>
                {
                    b.Property<int>("FinalProjectStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowSetByPartner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FinalProjectStatusId");

                    b.ToTable("FinalProjectStatuses");

                    b.HasData(
                        new
                        {
                            FinalProjectStatusId = 1,
                            AllowSetByPartner = false,
                            Name = "Not Started"
                        },
                        new
                        {
                            FinalProjectStatusId = 2,
                            AllowSetByPartner = false,
                            Name = "In Progress"
                        },
                        new
                        {
                            FinalProjectStatusId = 3,
                            AllowSetByPartner = false,
                            Name = "Submitted"
                        },
                        new
                        {
                            FinalProjectStatusId = 4,
                            AllowSetByPartner = false,
                            Name = "Passed"
                        },
                        new
                        {
                            FinalProjectStatusId = 5,
                            AllowSetByPartner = false,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.InviteCode", b =>
                {
                    b.Property<Guid>("InviteCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedeemedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("InviteCodeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RedeemedByUserId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.KemKeyPair", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("KemKeyPairs");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Major", b =>
                {
                    b.Property<Guid>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("TEXT");

                    b.HasKey("MajorId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ModeOfStudy", b =>
                {
                    b.Property<int>("ModeOfStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ModeOfStudyId");

                    b.ToTable("ModesOfStudy");

                    b.HasData(
                        new
                        {
                            ModeOfStudyId = 1,
                            Name = "Distance/Online Self-Study"
                        },
                        new
                        {
                            ModeOfStudyId = 2,
                            Name = "Blended Learning"
                        },
                        new
                        {
                            ModeOfStudyId = 3,
                            Name = "Full-Time On-Campus"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.OpaqueCredential", b =>
                {
                    b.Property<Guid>("OpaqueCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ClientPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OprfSeed")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OpaqueCredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OpaqueCredentials");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.OpaqueRecoveryCode", b =>
                {
                    b.Property<Guid>("OpaqueRecoveryCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ClientPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OprfSeed")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OpaqueRecoveryCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("OpaqueRecoveryCodes");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Partner", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPersonEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPersonPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPersonTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContractEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContractStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.PartnerProgrammeAccess", b =>
                {
                    b.Property<Guid>("PartnerProgrammeAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisabledByPartner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerProgrammeAccessId");

                    b.HasIndex("MajorId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("PartnerId", "MajorId", "DeletedAt");

                    b.ToTable("PartnerProgrammeAccesses");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Pathway", b =>
                {
                    b.Property<int>("PathwayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PathwayId");

                    b.ToTable("Pathways");

                    b.HasData(
                        new
                        {
                            PathwayId = 1,
                            Name = "Pathway 1: Direct Entry via Bachelor's Degree"
                        },
                        new
                        {
                            PathwayId = 2,
                            Name = "Pathway 2: Advanced Diploma + 3 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 3,
                            Name = "Pathway 3: Diploma + 5 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 4,
                            Name = "Pathway 4: High School + 8 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 5,
                            Name = "Pathway 1: Master's Degree (Preferred Entry)"
                        },
                        new
                        {
                            PathwayId = 6,
                            Name = "Pathway 2: Bachelor's Degree + 5 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 7,
                            Name = "Pathway 3: Advanced Diploma + 7 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 8,
                            Name = "Pathway 4: Diploma + 9 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 9,
                            Name = "Pathway 5: High School + 12 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 10,
                            Name = "Open Entry"
                        },
                        new
                        {
                            PathwayId = 11,
                            Name = "Pathway 1: Diploma or Associate Degree"
                        },
                        new
                        {
                            PathwayId = 12,
                            Name = "Pathway 2: High School Certificate + 3 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 13,
                            Name = "Pathway 1: Advanced Diploma"
                        },
                        new
                        {
                            PathwayId = 14,
                            Name = "Pathway 2: Diploma + 2 Years Work Exp"
                        },
                        new
                        {
                            PathwayId = 15,
                            Name = "Pathway 3: High School Certificate + 5 Years Work Exp"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.PathwayDocumentRequirement", b =>
                {
                    b.Property<Guid>("PathwayDocumentRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PathwayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PathwayDocumentRequirementId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PathwayId", "DocumentTypeId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PathwayDocumentRequirements");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Programme", b =>
                {
                    b.Property<Guid>("ProgrammeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClonedFromProgrammeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabledByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProgrammeId");

                    b.HasIndex("ClonedFromProgrammeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartnerId", "Status");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ProgrammeDocumentRequirement", b =>
                {
                    b.Property<Guid>("ProgrammeDocumentRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MajorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProgrammeDocumentRequirementId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("MajorId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("ProgrammeDocumentRequirements");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ProgrammePathway", b =>
                {
                    b.Property<Guid>("ProgrammePathwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PathwayId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProgrammePathwayId");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProgrammeId", "PathwayId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("ProgrammePathways");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.SessionToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SessionTokens");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestDegree")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageResult")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsWorkExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentDocument", b =>
                {
                    b.Property<Guid>("StudentDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentDocumentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", b =>
                {
                    b.Property<Guid>("StudentEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdmissionConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CertReleased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CommencementDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationOfStudyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnrollmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MissingDocsSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeOfStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherFeesStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PathwayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDoneAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TranscriptReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TuitionFeeStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentEnrollmentId");

                    b.HasIndex("EnrollmentStatusId");

                    b.HasIndex("MajorId");

                    b.HasIndex("ModeOfStudyId");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TuitionFeeStatusId");

                    b.ToTable("StudentEnrollments");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentNote", b =>
                {
                    b.Property<Guid>("StudentNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentEnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNoteId");

                    b.HasIndex("StudentEnrollmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNotes");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ects")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.HasIndex("MajorId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.SubjectGrade", b =>
                {
                    b.Property<Guid>("SubjectGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectGradeId");

                    b.HasIndex("StudentEnrollmentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectGrades");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.TuitionFeeStatus", b =>
                {
                    b.Property<int>("TuitionFeeStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TuitionFeeStatusId");

                    b.ToTable("TuitionFeeStatuses");

                    b.HasData(
                        new
                        {
                            TuitionFeeStatusId = 1,
                            Name = "Unpaid"
                        },
                        new
                        {
                            TuitionFeeStatusId = 2,
                            Name = "Partially Paid"
                        },
                        new
                        {
                            TuitionFeeStatusId = 3,
                            Name = "Fully Paid"
                        },
                        new
                        {
                            TuitionFeeStatusId = 4,
                            Name = "Not Applicable"
                        });
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserAddress", b =>
                {
                    b.Property<Guid>("UserAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserContactEmail", b =>
                {
                    b.Property<Guid>("UserContactEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserContactEmailId");

                    b.HasIndex("UserId");

                    b.ToTable("UserContactEmails");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserPhone", b =>
                {
                    b.Property<Guid>("UserPhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserPhoneId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPhones");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserTwoFactorMethod", b =>
                {
                    b.Property<Guid>("UserTwoFactorMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastTotpStepUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MethodType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserTwoFactorMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTwoFactorMethods");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.EnrollmentDocument", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.StudentDocument", "StudentDocument")
                        .WithMany()
                        .HasForeignKey("StudentDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", "StudentEnrollment")
                        .WithMany("EnrollmentDocuments")
                        .HasForeignKey("StudentEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("DocumentType");

                    b.Navigation("StudentDocument");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Fido2Credential", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.FinalProject", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.FinalProjectStatus", "FinalProjectStatus")
                        .WithMany()
                        .HasForeignKey("FinalProjectStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", "StudentEnrollment")
                        .WithOne("FinalProject")
                        .HasForeignKey("SharedLibrary.Basics.Opaque.Domains.FinalProject", "StudentEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalProjectStatus");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.InviteCode", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "RedeemedByUser")
                        .WithMany()
                        .HasForeignKey("RedeemedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("RedeemedByUser");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.KemKeyPair", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Major", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "Programme")
                        .WithMany("Majors")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.OpaqueCredential", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.OpaqueRecoveryCode", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Partner", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.PartnerProgrammeAccess", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Partner");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.PathwayDocumentRequirement", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Pathway");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Programme", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "ClonedFromProgramme")
                        .WithMany()
                        .HasForeignKey("ClonedFromProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClonedFromProgramme");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ProgrammeDocumentRequirement", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Major");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.ProgrammePathway", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathway");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.SessionToken", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Student", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentDocument", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocumentType");

                    b.Navigation("Student");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.EnrollmentStatus", "EnrollmentStatus")
                        .WithMany()
                        .HasForeignKey("EnrollmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ModeOfStudy", "ModeOfStudy")
                        .WithMany()
                        .HasForeignKey("ModeOfStudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.TuitionFeeStatus", "TuitionFeeStatus")
                        .WithMany()
                        .HasForeignKey("TuitionFeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnrollmentStatus");

                    b.Navigation("Major");

                    b.Navigation("ModeOfStudy");

                    b.Navigation("Pathway");

                    b.Navigation("Programme");

                    b.Navigation("Student");

                    b.Navigation("TuitionFeeStatus");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentNote", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", "StudentEnrollment")
                        .WithMany()
                        .HasForeignKey("StudentEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Subject", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Major", "Major")
                        .WithMany("Subjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.SubjectGrade", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", "StudentEnrollment")
                        .WithMany("SubjectGrades")
                        .HasForeignKey("StudentEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentEnrollment");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserAddress", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserContactEmail", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserPhone", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserProfile", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.UserTwoFactorMethod", b =>
                {
                    b.HasOne("SharedLibrary.Basics.Opaque.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Major", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Programme", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.Student", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Enrollments");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SharedLibrary.Basics.Opaque.Domains.StudentEnrollment", b =>
                {
                    b.Navigation("EnrollmentDocuments");

                    b.Navigation("FinalProject");

                    b.Navigation("SubjectGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
