using System.Security.Claims;
using Odin.Api.Base.Authorization;
using Odin.Api.Base.Letters;

namespace School.PartnerAdminApi.Admin.V1.Students.Endpoint;

/// <summary>
/// Re-releases letters already issued for an enrolment, so the PDFs pick up
/// changed tag data (typically an admin duration override that shifts the
/// completion date). Pass <c>?letterType=OfferLetter</c> to regenerate just
/// one letter (the per-row "Regenerate" button); omit it to regenerate every
/// released type. Only letter types with at least one previously released
/// document are regenerated; nothing is issued for the first time here.
/// Restricted to Administrator and SuperAdministrator, matching the
/// duration-override endpoint that motivates the re-release. Exception: the
/// final-project approval letters (proposal/project) may be generated by any
/// non-read-only admin level, since issuing them is routine Admission work.
/// </summary>
[Route("/v1/admin/students/{studentId:guid}/enrollments/{enrollmentId:guid}/letters/regenerate")]
[EndpointTag("Admin.Students")]
public sealed class AdminV1StudentsRegenerateLettersEndpoint : IEndpointMarker
{
    public IEndpointRouteBuilder Map(IEndpointRouteBuilder app)
    {
        app.MapPatch("/v1/school/programmes/{programmeId:guid}/project-pass-mark", PassMarkAsync)
            .RequireAuthorization("AdminOnly");
        app.MapPost("/v1/admin/students/{studentId:guid}/enrollments/{enrollmentId:guid}/letters/regenerate", HandleAsync)
            .RequireAuthorization("AdminOnly");
        return app;
    }

    private static readonly (Guid DocumentTypeId, LetterType LetterType)[] LetterDocTypes =
    [
        (SystemDocumentTypeIds.OfferLetter,            LetterType.OfferLetter),
        (SystemDocumentTypeIds.AdmissionLetter,        LetterType.AdmissionLetter),
        (SystemDocumentTypeIds.Transcript,             LetterType.Transcript),
        (SystemDocumentTypeIds.PrintableTranscript,    LetterType.PrintableTranscript),
        (SystemDocumentTypeIds.Certificate,            LetterType.Certificate),
        (SystemDocumentTypeIds.ProvisionalCertificate, LetterType.ProvisionalCertificate),
        (SystemDocumentTypeIds.StudentIdCard,          LetterType.StudentIdCard),
        (SystemDocumentTypeIds.FinalProposalApproval,  LetterType.FinalProposalApproval),
        (SystemDocumentTypeIds.FinalProjectApproval,   LetterType.FinalProjectApproval),
    ];

    private static async Task<IResult> HandleAsync(
        Guid studentId, Guid enrollmentId,
        [FromQuery] string? letterType,
        [FromQuery] string? language,
        HttpContext httpContext,
        [FromServices] UserManager<ApplicationUser> userManager,
        [FromServices] IPermissionService perms,
        LetterReleaseService letterRelease,
        OdinDbContext db, CancellationToken ct)
    {
        var callerId = httpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (string.IsNullOrEmpty(callerId)) return Results.Unauthorized();
        var caller = await userManager.FindByIdAsync(callerId);
        if (caller is null || caller.DeletedAt is not null || !caller.IsEnabled)
            return Results.Unauthorized();

        // Config-created (dynamic) letter type: {letterType} carries the
        // definition GUID. Routine admission work like the approval letters,
        // so any non-read-only admin level may generate; every render appends
        // a Manual version row with the caller's name.
        if (Guid.TryParse(letterType, out var definitionId))
        {
            var isReadOnlyCaller = await userManager.IsInRoleAsync(caller, AdminLevels.Viewer)
                || await userManager.IsInRoleAsync(caller, AdminLevels.Sales);
            if (isReadOnlyCaller)
                return Results.Json(new { error = "Read-only access cannot generate letters." }, statusCode: StatusCodes.Status403Forbidden);
            var ownsEnrolment = await db.Enrollments.AnyAsync(e => e.StudentEnrollmentId == enrollmentId
                && e.StudentId == studentId && e.DeletedAt == null, ct);
            if (!ownsEnrolment) return Results.NotFound();
            var defName = await db.LetterTypeDefinitions
                .Where(d => d.LetterTypeDefinitionId == definitionId && d.DeletedAt == null)
                .Select(d => d.Name).FirstOrDefaultAsync(ct);
            if (defName is null) return Results.BadRequest(new { error = "Unknown letter type." });
            var docId = await letterRelease.ReleaseDynamicAsync(
                enrollmentId, definitionId, language, "Manual", caller.UserName, callerId,
                letterTypeHint: null, ct);
            return Results.Ok(new { regenerated = docId is null ? Array.Empty<string>() : new[] { defName } });
        }

        // Optional single-letter filter (the per-row "Regenerate" button).
        LetterType? onlyType = null;
        if (!string.IsNullOrWhiteSpace(letterType))
        {
            if (!Enum.TryParse<LetterType>(letterType, ignoreCase: true, out var parsed))
                return Results.BadRequest(new { error = $"Unknown letter type '{letterType}'." });
            onlyType = parsed;
        }

        // The final-project approval letters are day-to-day Admission Office
        // work: any non-read-only admin level may generate them. Everything
        // else stays Administrator+ like the duration override.
        var isAdministrator = await perms.HasAsync(httpContext.User, AdminPermissions.StudentsRegenerateLetters, ct);
        if (!isAdministrator)
        {
            var isApprovalLetter = onlyType is LetterType.FinalProposalApproval or LetterType.FinalProjectApproval;
            if (!isApprovalLetter)
                return Results.Json(new { error = "Requires Administrator level or above." }, statusCode: StatusCodes.Status403Forbidden);
            var isReadOnly = await userManager.IsInRoleAsync(caller, AdminLevels.Viewer)
                || await userManager.IsInRoleAsync(caller, AdminLevels.Sales);
            if (isReadOnly)
                return Results.Json(new { error = "Read-only access cannot generate letters." }, statusCode: StatusCodes.Status403Forbidden);
        }

        var enrolment = await db.Enrollments
            .Where(e => e.StudentEnrollmentId == enrollmentId
                && e.StudentId == studentId
                && e.DeletedAt == null)
            .Select(e => new
            {
                IssueCard = db.Programmes
                    .Where(p => p.ProgrammeId == e.Specialization.ProgrammeId)
                    .Select(p => p.IssueDigitalStudentCard)
                    .FirstOrDefault(),
            })
            .FirstOrDefaultAsync(ct);
        if (enrolment is null) return Results.NotFound();

        var releasedDocTypeIds = await db.StudentDocuments
            .Where(d => d.EnrollmentId == enrollmentId && d.DeletedAt == null)
            .Select(d => d.DocumentTypeId)
            .Distinct()
            .ToListAsync(ct);

        var regenerated = new List<string>();
        foreach (var (docTypeId, type) in LetterDocTypes)
        {
            if (onlyType is not null && type != onlyType) continue;
            // The student ID card only exists for programmes that opted in.
            if (type == LetterType.StudentIdCard && !enrolment.IssueCard) continue;
            // "Regenerate all" (no explicit type) only re-renders letters already
            // released. An explicit single-letter request (the per-row Generate
            // button) may issue one for the first time — used to back-fill a
            // missing Printable Cert / Digital Certificate after grading.
            if (onlyType is null && !releasedDocTypeIds.Contains(docTypeId)) continue;
            var newDocId = await letterRelease.ReleaseAsync(enrollmentId, type, ct);
            if (newDocId is not null) regenerated.Add(type.ToString());
        }

        return Results.Ok(new { regenerated });
    }

    public sealed class PassMarkBody { public int PassMark { get; init; } }

    /// <summary>Per-programme pass mark for the final-project approval
    /// letters (default 40): a proposal/project cohort mark at or above it
    /// releases the matching approval letter automatically.</summary>
    private static async Task<IResult> PassMarkAsync(
        Guid programmeId, [FromBody] PassMarkBody body,
        HttpContext httpContext, [FromServices] IPermissionService perms,
        OdinDbContext db, CancellationToken ct)
    {
        if (await perms.AccessAsync(httpContext.User, "student.letters.passmark", ct) != AccessLevel.Edit) return Results.Forbid();

        if (body.PassMark is < 0 or > 100)
            return Results.BadRequest(new { error = "Pass mark must be between 0 and 100." });
        var programme = await db.Programmes.FirstOrDefaultAsync(p => p.ProgrammeId == programmeId && p.DeletedAt == null, ct);
        if (programme is null) return Results.NotFound();
        programme.ProjectApprovalPassMark = body.PassMark;
        await db.SaveChangesAsync(ct);
        return Results.Ok(new { programmeId, passMark = programme.ProjectApprovalPassMark });
    }
}
